/**
 * Source data: 350 tim olimpiade yang akan di-assign ke 2 sesi
 * Format: [no, nama tim, asal sekolah, sesi]
 * Diambil verbatim dari input user.
 */

export type SessionAssignment = {
  no: number;
  name: string;
  school: string;
  session: 1 | 2;
};

export const SESSION_TEAMS_RAW: SessionAssignment[] = [
  { no: 1, name: "Solstice", school: "SMA Global Islamic School 2 Serpong", session: 1 },
  { no: 2, name: "TRISULA BIRU", school: "MAS AL HIKMAH 2", session: 1 },
  { no: 3, name: "alphabetagammadelta1", school: "SMAN 1 Kota Depok", session: 1 },
  { no: 4, name: "kusuka jagung amerika", school: "SMA Trensains Tebuireng", session: 1 },
  { no: 5, name: "CAMABA UNAIR 2027", school: "SMA TUNAS LUHUR", session: 1 },
  { no: 6, name: "bismillah siap mantap", school: "SMAS Syafana Islamic School", session: 1 },
  { no: 7, name: "WarMTek(Warga Matematika Teknik)", school: "SMAIT NFBS Bogor", session: 1 },
  { no: 8, name: "Beeology", school: "SMA BINUS SCHOOL Serpong", session: 1 },
  { no: 9, name: "Tim raivmaysains", school: "SMAS Unggulan Haf-sa BPPT Genggong", session: 1 },
  { no: 10, name: "vicieuy", school: "SMAS Khadijah Surabaya", session: 1 },
  { no: 11, name: "Tries", school: "SMA Negeri 1 Ngawi", session: 1 },
  { no: 12, name: "FOURBIO", school: "SMA Negeri 4 Denpasar", session: 1 },
  { no: 13, name: "Athbone_27", school: "SMA Islam Athirah Bone", session: 1 },
  { no: 14, name: "3 pilar kehidupan", school: "SMAN 1 NGAWI", session: 1 },
  { no: 15, name: "GZV", school: "SMA Alta Global School", session: 1 },
  { no: 16, name: "Sayang Ayah Ibu", school: "SMA Negeri 2 Lumajang", session: 1 },
  { no: 17, name: "The Aesthale", school: "SMA Kristen Petra 1", session: 1 },
  { no: 18, name: "Tim Panacea", school: "SMA Negeri 1 Kintamani", session: 1 },
  { no: 19, name: "SSFN", school: "SMA 3 Bahasa Putera Harapan", session: 1 },
  { no: 20, name: "TIM TRENSAINS", school: "SMA Trensains Tebuireng", session: 1 },
  { no: 21, name: "Tim GEN SMANDA", school: "SMA Negeri 2 Sidoarjo", session: 1 },
  { no: 22, name: "Tim Gisel", school: "SMA Negeri 11 Surabaya", session: 1 },
  { no: 23, name: "velvet", school: "SMAS UNGGULAN HAF-SA BBPT GENGGONG", session: 1 },
  { no: 24, name: "Candra metrika", school: "Sma negeri 1 kawedanan", session: 1 },
  { no: 25, name: "GenomeXVII", school: "SMAN 17 Surabaya", session: 1 },
  { no: 26, name: "HelloWorld(“print”)", school: "SMA NEGERI 1 Probolinggo", session: 1 },
  { no: 27, name: "Onigiri Kantin K2", school: "SMA ABBS SURAKARTA", session: 1 },
  { no: 28, name: "Mall-e", school: "SMA Bintang Madani (OMNI School)", session: 1 },
  { no: 29, name: "bismillah lolos", school: "SMAN 15 Surabaya", session: 1 },
  { no: 30, name: "Tim BSN Sigma", school: "SMA Negeri 2 Purworejo", session: 1 },
  { no: 31, name: "Tim SMASA", school: "SMA Negeri 1 Pasuruan", session: 1 },
  { no: 32, name: "seadanya", school: "SMA Negeri 1 Ngawi", session: 1 },
  { no: 33, name: "The Adaptors", school: "SMAS Unggulan Amanatul Ummah", session: 1 },
  { no: 34, name: "DARDERDOR", school: "SMA Negeri 5 Surabaya", session: 1 },
  { no: 35, name: "Olim asbosh putri", school: "SMAS IT As-Syifa Boarding School", session: 1 },
  { no: 36, name: "bismillahgaspoll", school: "SMA NEGERI 1 KOTA PROBOLINGGO", session: 1 },
  { no: 37, name: "Synapses", school: "SMA Negeri 8 Jakarta", session: 1 },
  { no: 38, name: "Dream Team", school: "SMAK Ipeka Sunter", session: 1 },
  { no: 39, name: "Trio IPA", school: "MAN 2 Sijunjung PLus Keterampilan", session: 1 },
  { no: 40, name: "OMEGA USA", school: "SMAS UNGGULANN HAF-SA ZAINUL HASAN", session: 1 },
  { no: 41, name: "hamster imut sirimut tikimut kimut", school: "SMA Negeri 1 Tegal", session: 1 },
  { no: 42, name: "Athbar", school: "SMA Islam Athirah Bukit Baruga", session: 1 },
  { no: 43, name: "biri-biri", school: "SMA Wachid Hasyim 2 Taman", session: 1 },
  { no: 44, name: "Tim Bismillahirrahmanirrahim", school: "MAN 1 MOJOKERTO", session: 1 },
  { no: 45, name: "Tim HACHI8", school: "SMA Negeri 8 Jakarta", session: 1 },
  { no: 46, name: "BioNova Smada", school: "SMA Negeri 2 Kediri", session: 1 },
  { no: 47, name: "Tim MAWCA", school: "SMA Laboratorium UM", session: 1 },
  { no: 48, name: "SMA Negeri 3 Bandung", school: "SMA Negeri 3 Bandung", session: 1 },
  { no: 49, name: "LUMINA", school: "SMA NEGERI 4 BOJONEGORO", session: 1 },
  { no: 50, name: "Si kody", school: "SMA Negeri 1 Ngunut", session: 1 },
  { no: 51, name: "Hamba Allah", school: "SMA Negeri 1 Ngunut", session: 1 },
  { no: 52, name: "UNAIRVers", school: "MAU AMANATUL UMMAH", session: 1 },
  { no: 53, name: "Extinct Declaration", school: "MAU AMANATUL UMMAH", session: 1 },
  { no: 54, name: "Melesat Alnesa", school: "MAN 1 Yogyakarta", session: 1 },
  { no: 55, name: "OLIMPIADE TEST 01", school: "SMA Test 1", session: 1 },
  { no: 56, name: "unicorn sparkle sparkle", school: "SMA 3 Bahasa Putera Harapan", session: 1 },
  { no: 57, name: "ISTANDS", school: "MBI Amanatul Ummah Pacet Mojokerto", session: 1 },
  { no: 58, name: "VeryHawt", school: "SMA Negeri 1 Sidoarjo", session: 1 },
  { no: 59, name: "Tim Hore", school: "SMA Negeri 1 Ngawi", session: 1 },
  { no: 60, name: "Veloura", school: "SMA NEGERI 19 SURABAYA", session: 1 },
  { no: 61, name: "LAOTUJU SCIENCE", school: "SMA Uggulan Haf-Sa Zainul Hasan BPPT Genggong", session: 1 },
  { no: 62, name: "ANFOREBLE", school: "SMA UNGGULAN HAF-SA ZAINUL HASAN BPPT GENGGONG", session: 1 },
  { no: 63, name: "Tim Hoki vip", school: "SMAN 3 PONOROGO", session: 1 },
  { no: 64, name: "Towewew", school: "SMAN 2 BONDOWOSO", session: 1 },
  { no: 65, name: "Fafayan", school: "MAN 2 Kudus", session: 1 },
  { no: 66, name: "Bissmillah", school: "SMA Negeri 1 bululawang", session: 1 },
  { no: 67, name: "DNA (Dynamic, Noble, and Academics)", school: "SMAN 1 NGAWI", session: 1 },
  { no: 68, name: "VETERNA", school: "SMAS AR ROHMAH DAU", session: 1 },
  { no: 69, name: "JuARayuk", school: "SMA Negeri 8 Jakarta", session: 1 },
  { no: 70, name: "AIRLAYSEVEN", school: "SMA Negeri 15 Surabaya", session: 1 },
  { no: 71, name: "Jagoan Sistem Kebut Semalam", school: "SMA Negeri 2 Bondowoso", session: 1 },
  { no: 72, name: "DOA EMAK", school: "SMA Negeri 2 Bondowoso", session: 1 },
  { no: 73, name: "MBG", school: "SMA Negeri 1 Yogyakarta", session: 1 },
  { no: 74, name: "Maesan Pejaten Menang", school: "SMA Negeri 2 Bondowoso", session: 1 },
  { no: 75, name: "Suki Gelap", school: "MAN Insan Cendekia Serpong", session: 1 },
  { no: 76, name: "tiga atom", school: "SMA Negeri 1 Krembung", session: 1 },
  { no: 77, name: "Smanigizen30", school: "SMAN 1 Gedangan", session: 1 },
  { no: 78, name: "MafiaSragen", school: "SMA Unggulan Rushd", session: 1 },
  { no: 79, name: "Tim NiNaNi SMALA", school: "SMA Negeri 5 Surabaya", session: 1 },
  { no: 80, name: "Tim KingJagoan", school: "SMA Regina Pacis Surakarta", session: 1 },
  { no: 81, name: "SMS", school: "SMA Negeri 2 Bondowoso", session: 1 },
  { no: 82, name: "antek antek asing", school: "SMAN 1 BULULAWANG", session: 1 },
  { no: 83, name: "lombacumabuatdapetsertifpeserta", school: "SMA Negeri 1 Surabaya", session: 1 },
  { no: 84, name: "Pinnacle", school: "SMA Negeri 4 Jember", session: 1 },
  { no: 85, name: "Trio Qul", school: "SMA Negeri 2 Kediri", session: 1 },
  { no: 86, name: "Zalcalogi", school: "SMA Negeri 1 Ngawi", session: 1 },
  { no: 87, name: "bioengineer", school: "SMA NEGERI 17 SURABAYA", session: 1 },
  { no: 88, name: "sinwinwar", school: "SMA ALFALAH KETINTANG SURABAYA", session: 1 },
  { no: 89, name: "nyailah", school: "SMA Negeri 1 Gresik", session: 1 },
  { no: 90, name: "guddey", school: "SMA LABSCHOOL UNESA 1", session: 1 },
  { no: 91, name: "MAS BILINGUAL", school: "MAS BILINGUAL AL-AMANAH", session: 1 },
  { no: 92, name: "semestars", school: "SMA Semesta", session: 1 },
  { no: 93, name: "Final Victor", school: "SMA NEGERI 21 SURABAYA", session: 1 },
  { no: 94, name: "SmamdaTung", school: "SMA MUHAMMADIYAH 2 SURABAYA", session: 1 },
  { no: 95, name: "Ngitung", school: "SMA NEGERI 1 GRESIK", session: 1 },
  { no: 96, name: "BismillahUner", school: "SMA negeri 1 Cirebon", session: 1 },
  { no: 97, name: "Tim hilang arah", school: "MA Negeri 2 Kudus", session: 1 },
  { no: 98, name: "mercy chewy melty", school: "MAS ISLAM TERPADU BAITUL QUR'AN AL JAHRA MAGETAN", session: 1 },
  { no: 99, name: "VIVIZ", school: "SMAS TRIMURTI SURABAYA", session: 1 },
  { no: 100, name: "Tim Barcelliny", school: "SMAS IT As-Syifa Boarding School Jalancagak", session: 1 },
  { no: 101, name: "Harmoni Hexagon", school: "SMA Negeri 1 Glagah", session: 1 },
  { no: 102, name: "SMANITRA 67", school: "SMA Negeri 1 Tangerang", session: 1 },
  { no: 103, name: "dhairadra", school: "SMA Negeri 1 Pemalang", session: 1 },
  { no: 104, name: "AUREA", school: "SMA Negeri 1 Gedangan", session: 1 },
  { no: 105, name: "POLARIS", school: "SMAS Islam Athirah Makassar", session: 1 },
  { no: 106, name: "Anak Emas Smasa Ngawi", school: "SMA Negeri 1 Ngawi", session: 1 },
  { no: 107, name: "BTBC", school: "SMA Negeri 1 Manyar", session: 1 },
  { no: 108, name: "VECTA", school: "SMA Bunda Mulia", session: 1 },
  { no: 109, name: "INVECTA", school: "SMA Negeri 1 Ngawi", session: 1 },
  { no: 110, name: "ayam assalamualaikum enjoyer", school: "SMA Negeri 5 Surabaya", session: 1 },
  { no: 111, name: "SMANDUTA Biomed Innovators", school: "SMA Negeri 2 Kuta", session: 1 },
  { no: 112, name: "itaiyo", school: "SMA Khadijah Surabaya", session: 1 },
  { no: 113, name: "G-TRIUMVORA", school: "SMA Negeri 1 Purbalingga", session: 1 },
  { no: 114, name: "CAMABA FK 28", school: "SMA Negeri 21 Surabaya", session: 1 },
  { no: 115, name: "Victory Team", school: "SMA Negeri 2 Lamongan", session: 1 },
  { no: 116, name: "Teripang (Trio Kesbang)", school: "SMA Kesatuan Bangsa Yogyakarta", session: 1 },
  { no: 117, name: "Rombongan Wong Tulus (RWT)", school: "MAIT BAITUL QUR'AN AL JAHRA MAGETAN", session: 1 },
  { no: 118, name: "Jaya Jaya Team", school: "SMA Negeri 1 Bangkalan", session: 1 },
  { no: 119, name: "SMANU MHT", school: "SMAN Unggulan M.H. Thamrin", session: 1 },
  { no: 120, name: "Infinity", school: "SMA Negeri 20 Surabaya", session: 1 },
  { no: 121, name: "Aureon", school: "SMA Negeri 1 Genteng", session: 1 },
  { no: 122, name: "Trioweks", school: "SMA Negeri 1 Sidoarjo", session: 1 },
  { no: 123, name: "KRYPTON", school: "MAN 2 Kudus", session: 1 },
  { no: 124, name: "Oksipital", school: "MAN 2 Pekanbaru", session: 1 },
  { no: 125, name: "JALENDRO", school: "SMA Negeri 1 Ngawi", session: 1 },
  { no: 126, name: "Tim Powerpuff", school: "SMA YADIKA 12", session: 1 },
  { no: 127, name: "Pasukan Imo", school: "SMA Negeri 2 Purworejo", session: 1 },
  { no: 128, name: "RootRangers", school: "SMA Negeri 1 Karanganyar", session: 1 },
  { no: 129, name: "unerblade", school: "SMA Negeri 1 Kudus", session: 1 },
  { no: 130, name: "LUMINACEN", school: "SMA Negeri 2 Madiun", session: 1 },
  { no: 131, name: "PASMEN", school: "MAN INSAN CENDEKIA SERPONG", session: 1 },
  { no: 132, name: "Tim JosJis", school: "SMA Negeri 20 Surabaya", session: 1 },
  { no: 133, name: "NAIRA", school: "SMA NEGERI 1 SURABAYA", session: 1 },
  { no: 134, name: "otwagit", school: "SMAN 1 KEPANJEN", session: 1 },
  { no: 135, name: "BioBelles", school: "SMA Muhammadiyah 10 GKB Gresik", session: 1 },
  { no: 136, name: "Boleh ngga pake nama tim ini?", school: "SMA Negeri 1 Krian", session: 1 },
  { no: 137, name: "BIOBADAG", school: "MAN 2 Blitar", session: 1 },
  { no: 138, name: "doea toedjoeh", school: "SMAS SANTO THOMAS 1 MEDAN", session: 1 },
  { no: 139, name: "Sanare Tres", school: "SMA NEGERI 1 TALUN", session: 1 },
  { no: 140, name: "semogalolossampeosp", school: "SMA NEGERI 1 SURABAYA", session: 1 },
  { no: 141, name: "Bismillah aja", school: "SMA Thursina IIBS Malang", session: 1 },
  { no: 142, name: "MASITA GENK", school: "SMA Negeri 2 Purworejo", session: 1 },
  { no: 143, name: "satu tim tiga otak", school: "SMAS KHADIJAH SURABAYA", session: 1 },
  { no: 144, name: "Tim Nomatos", school: "SMA MUHAMMADIYAH 2 Surabaya", session: 1 },
  { no: 145, name: "NOYYOREN", school: "SMA Negeri 1 Ponorogo", session: 1 },
  { no: 146, name: "The Science Conqueror", school: "SMA Negeri 27 Kabupaten Tangerang", session: 1 },
  { no: 147, name: "The pixie-eye", school: "SMA Fitrah Islamic World academy", session: 1 },
  { no: 148, name: "tim biocentrix", school: "Man 2 Kudus", session: 1 },
  { no: 149, name: "Nastar", school: "SMA Negeri 1 Bangkalan", session: 1 },
  { no: 150, name: "elijibel girls", school: "SMA FIBBIS (FITHRAH INSANI BILINGUAL BOARDING ISLAMIC SCHOOL)", session: 1 },
  { no: 151, name: "nerds project", school: "SMA Negeri 20 Surabaya", session: 1 },
  { no: 152, name: "Cherrybelle", school: "SMA Negeri 2 Purwokerto", session: 1 },
  { no: 153, name: "Mitochondriaz", school: "SMAK Mgr. Soegijapranata Pasuruan", session: 1 },
  { no: 154, name: "IBUPROFEN", school: "SMA Pradita Dirgantara", session: 1 },
  { no: 155, name: "The Prosthetic Pioneers", school: "SMA Negeri 1 Pati", session: 1 },
  { no: 156, name: "GAZZ", school: "SMAN 1 SUMENEP", session: 1 },
  { no: 157, name: "Tim Punuk Unta", school: "SMA Negeri 4 Bekasi", session: 1 },
  { no: 158, name: "Lontong Sagu😂", school: "SMAN 5 Surabaya", session: 1 },
  { no: 159, name: "Jiwa Taruna Medika", school: "MAN 5 JOMBANG", session: 1 },
  { no: 160, name: "pokok smada", school: "SMAN 2 KOTA KEDIRI", session: 1 },
  { no: 161, name: "gua males mikir", school: "SMAN 3 Bogor", session: 1 },
  { no: 162, name: "Kaum Linjur", school: "SMA Negeri 7 Malang", session: 1 },
  { no: 163, name: "Mansavanguard", school: "MAN 1 Gresik", session: 1 },
  { no: 164, name: "Ctrl+Alt+Defeat (CAD)", school: "SMA YPI Darussalam", session: 1 },
  { no: 165, name: "Disuruh Pak Najih", school: "MAN 2 KUDUS", session: 1 },
  { no: 166, name: "SMA FIBBIS GACOR", school: "SMA FITHRAH INSANI BILINGUAL BOARDING ISLAMIC SCHOOL", session: 1 },
  { no: 167, name: "macanputih", school: "SMA Negeri 2 Kediri", session: 1 },
  { no: 168, name: "SMAeLKISI", school: "SMAS eLKISI", session: 1 },
  { no: 169, name: "Synapse Shift", school: "SMA Negeri 1 Glagah", session: 1 },
  { no: 170, name: "LincahTegesSregep", school: "SMA Trimurti Surabaya", session: 1 },
  { no: 171, name: "Proyek Bedah Soal", school: "SMAS Muhammadiyah 2 Surabaya", session: 1 },
  { no: 172, name: "IRM Ridho Allah", school: "MAN 2 MOJOKERTO", session: 1 },
  { no: 173, name: "TIM HAWT", school: "SMA Negeri 1 Sidoarjo", session: 1 },
  { no: 174, name: "TIM LANV", school: "SMA SWASTA KATOLIK KABANJAHE", session: 1 },
  { no: 175, name: "Alfazar Gacor", school: "SMA Negeri 2 Ngawi", session: 1 },
  { no: 176, name: "cilukba", school: "SMA Negeri 1 Pati", session: 2 },
  { no: 177, name: "Wise Men", school: "SMA NEGERI 1 TANGERANG", session: 2 },
  { no: 178, name: "Tim ESWL (Eh Semoga Win Lah)", school: "SMA Negeri 3 Depok", session: 2 },
  { no: 179, name: "Satisebo", school: "SMA Islam Al Azhar 4", session: 2 },
  { no: 180, name: "mabarolim", school: "MAN KOTA PASURUAN", session: 2 },
  { no: 181, name: "Triadoksli", school: "SMA AL-AZHAR SYIFA BUDI PARAHYANGAN", session: 2 },
  { no: 182, name: "Define Aura", school: "SMAS KATOLIK SANTO YOSEPH DENPASAR", session: 2 },
  { no: 183, name: "ayamciken", school: "SMAN 15 Surabaya", session: 2 },
  { no: 184, name: "Hompipa", school: "SMA Negeri 15 Surabaya", session: 2 },
  { no: 185, name: "The Tritans", school: "SMA Negeri 1 Taman", session: 2 },
  { no: 186, name: "MartabakMetastasis", school: "SMA Negeri 4 Purworejo", session: 2 },
  { no: 187, name: "ELARION", school: "SMA NEGERI 1 SUMBERREJO", session: 2 },
  { no: 188, name: "Circut&Cells", school: "SMA Global Islamic School 2 Serpong", session: 2 },
  { no: 189, name: "TEVRA", school: "SMA Negeri 1 Banggai", session: 2 },
  { no: 190, name: "SAUR Bogor", school: "SMAN 1 Bogor", session: 2 },
  { no: 191, name: "Tim Lontong Balap", school: "SMA Negeri 1 Ngunut", session: 2 },
  { no: 192, name: "the.hooke", school: "SMA N 5 TUALANG", session: 2 },
  { no: 193, name: "Trio Wek Wek", school: "SMA Negeri 2 Pare", session: 2 },
  { no: 194, name: "SOGEH", school: "SMA Negeri 3 Malang", session: 2 },
  { no: 195, name: "Tupai Berpikir", school: "SMA Nation Star Academy", session: 2 },
  { no: 196, name: "bubadibako", school: "SMA Negeri 20 Surabaya", session: 2 },
  { no: 197, name: "TIM BFF", school: "SMAN 1 Sooko", session: 2 },
  { no: 198, name: "Cembiocys", school: "MAN 2 Tulungagung", session: 2 },
  { no: 199, name: "trio sugeh", school: "SMA Negeri 3 Surakarta", session: 2 },
  { no: 200, name: "Sudden Shower", school: "SMAS Al Islam Krian", session: 2 },
  { no: 201, name: "Immanuel", school: "SMA Kebangsaan", session: 2 },
  { no: 202, name: "Tim Avellence", school: "MAN 1 KOTA MALANG", session: 2 },
  { no: 203, name: "aigo jinjja", school: "SMA Negeri 1 Sidoarjo", session: 2 },
  { no: 204, name: "gacor anti gedor", school: "SMA Negeri 1 Genteng", session: 2 },
  { no: 205, name: "Bionova", school: "SMA Negeri 1 Pasuruan", session: 2 },
  { no: 206, name: "trio grasak", school: "SMA ALFALAH KETINTANG SURABAYA", session: 2 },
  { no: 207, name: "MANSATARA", school: "MAN 1 Tangerang", session: 2 },
  { no: 208, name: "Tim tigasekawan", school: "SMAN 1 Sooko Mojokerto", session: 2 },
  { no: 209, name: "EsTehmAnis", school: "SMA Santo Thomas 1 Medan", session: 2 },
  { no: 210, name: "BISMILLAHSUKSES", school: "SMA Negeri 1 Sooko", session: 2 },
  { no: 211, name: "Bismillah Bejo", school: "SMA Negeri 1 Bangil", session: 2 },
  { no: 212, name: "Zenith Team", school: "SMAN 1 Dawarblandong", session: 2 },
  { no: 213, name: "Tim Saya Akan Lawan", school: "SMA Negeri 1 Mempawah Hilir", session: 2 },
  { no: 214, name: "Pertamax16k", school: "SMA Negeri 1 Sooko", session: 2 },
  { no: 215, name: "The Walkovers", school: "SMA Negeri 1 Malang", session: 2 },
  { no: 216, name: "The First Penguin", school: "MAN 1 Yogyakarta", session: 2 },
  { no: 217, name: "Tri Nocturna Smanda", school: "SMA Negeri 2 Purworejo", session: 2 },
  { no: 218, name: "wongsukses", school: "SMA NEGERI 20 SURABAYA", session: 2 },
  { no: 219, name: "Astfirka Team", school: "SMA Al-Maahira IIBS Malang", session: 2 },
  { no: 220, name: "Cakrawala", school: "MAN 1 Pasuruan", session: 2 },
  { no: 221, name: "cmamats", school: "SMA Negeri 1 Gresik", session: 2 },
  { no: 222, name: "Ayam Bakar Sambel Ijo", school: "SMA Negeri 4 Purworejo", session: 2 },
  { no: 223, name: "PELARIAN OSN", school: "SMA Negeri 1 Kota Tangerang", session: 2 },
  { no: 224, name: "zenith", school: "SMA Negeri 1 Pamekasan", session: 2 },
  { no: 225, name: "SMATER D'BOS", school: "SMAS FRATER DON BOSCO LEWOLEBA", session: 2 },
  { no: 226, name: "bmec bmnya bismillah menang", school: "SMA Al Hikmah Surabaya", session: 2 },
  { no: 227, name: "Nexora", school: "SMA Negeri 1 Ngawi", session: 2 },
  { no: 228, name: "Bionic-smansagan", school: "SMAN 1 Grobogan", session: 2 },
  { no: 229, name: "Mudik ke bulan", school: "MAN 2 Kota Kediri", session: 2 },
  { no: 230, name: "Wong Menangan", school: "Sma Negeri 2 Mojokerto", session: 2 },
  { no: 231, name: "SMANSCIENCE", school: "SMA Negeri 1 Sumenep", session: 2 },
  { no: 232, name: "Tim SaKiD", school: "SMA Global Islamic School 2", session: 2 },
  { no: 233, name: "MODAL DOA", school: "SMAN 21 MAKASSAR", session: 2 },
  { no: 234, name: "NeurONE SMANSAGAN", school: "SMA Negeri 1 Grobogan", session: 2 },
  { no: 235, name: "Tim catalys", school: "SMA negeri 3 Sidoarjo", session: 2 },
  { no: 236, name: "Braintormers", school: "SMA Negeri 1 Bululawang", session: 2 },
  { no: 237, name: "Tim Tirtagia", school: "SMA NEGERI 1 SIDOARJO", session: 2 },
  { no: 238, name: "KUA ASAM PART 2", school: "SMA Negeri 3 Luwuk", session: 2 },
  { no: 239, name: "Tim Maleo Smantil", school: "SMA Negeri 3 Luwuk", session: 2 },
  { no: 240, name: "Helion", school: "SMA NEGERI 3 LUWUK", session: 2 },
  { no: 241, name: "Bismillah Winner", school: "MAN Sidoarjo", session: 2 },
  { no: 242, name: "katanya digidaw aja", school: "SMA Negeri 20 Surabaya", session: 2 },
  { no: 243, name: "slurp", school: "SMA NEGERI 1 SINGARAJA", session: 2 },
  { no: 244, name: "ABS", school: "SMA Negeri 2 Depok", session: 2 },
  { no: 245, name: "HexHepta", school: "SMA Wardaya", session: 2 },
  { no: 246, name: "ikan kembung", school: "SMA Negeri 1 Sidoarjo", session: 2 },
  { no: 247, name: "keong gasyor", school: "MAN Batam", session: 2 },
  { no: 248, name: "SFC", school: "SMA Kusuma Bangsa", session: 2 },
  { no: 249, name: "Sigma67", school: "SMA KATOLIK SANTO LOUIS 1 SURABAYA", session: 2 },
  { no: 250, name: "Catalyst", school: "SMA Katolik Sinlui 1 Surabaya", session: 2 },
  { no: 251, name: "BioWeaPow", school: "SMA Negeri 3 Surakarta", session: 2 },
  { no: 252, name: "WinnerWinnerSugmaRizz", school: "Sma Global Mandiri Jakarta", session: 2 },
  { no: 253, name: "Insan Sehat", school: "SMA Negeri 1 Krian", session: 2 },
  { no: 254, name: "bebas aja", school: "SMA Negeri 1 Jember", session: 2 },
  { no: 255, name: "Kd yay", school: "SMA KHADIJAH SURABAYA", session: 2 },
  { no: 256, name: "Alpha Sains", school: "SMA NEGERI 1 LAWANG", session: 2 },
  { no: 257, name: "Asian people", school: "SMA Negeri 3 Surakarta", session: 2 },
  { no: 258, name: "cihuy", school: "SMAS KHADIJAH", session: 2 },
  { no: 259, name: "The CytoSquad", school: "SMA Sekolah Dian Harapan Holland Village", session: 2 },
  { no: 260, name: "Helo...", school: "SMAK ST LOUIS 1 Surabaya", session: 2 },
  { no: 261, name: "POWER PUFF GIRLS", school: "SMA Negeri 1 Bandar Lampung", session: 2 },
  { no: 262, name: "Rela United", school: "SMA NEGERI 1 PASURUAN", session: 2 },
  { no: 263, name: "Luminary", school: "SMA Negeri 1 Puncu", session: 2 },
  { no: 264, name: "Trio sugih", school: "SMA AL-Falah Ketintang Surabaya", session: 2 },
  { no: 265, name: "TIM CHAWONCHAN", school: "SMA TRIMURTI SURABAYA", session: 2 },
  { no: 266, name: "mamah aku bmec", school: "SMA Negeri 1 Bululawang", session: 2 },
  { no: 267, name: "Trio Sigma", school: "SMA Negeri 4 Sidoarjo", session: 2 },
  { no: 268, name: "Suganwe", school: "SMA Negeri 8 Bandung", session: 2 },
  { no: 269, name: "Kedokteran Nuklir", school: "SMA Negeri 4 Semarang", session: 2 },
  { no: 270, name: "Amorfati", school: "SMA NEGERI 1 PACIRAN", session: 2 },
  { no: 271, name: "Golden Trio", school: "SMA NEGERI 3 KOTA TANGERANG SELATAN", session: 2 },
  { no: 272, name: "Tim WEI's Circle", school: "SMA Negeri 1 Babat", session: 2 },
  { no: 273, name: "Satu Raja Dua Rakyat", school: "SMAN 1 Cianjur", session: 2 },
  { no: 274, name: "Genastra", school: "MAN 1 Pasuruan", session: 2 },
  { no: 275, name: "overcooked", school: "SMA Negeri 16 Surabaya", session: 2 },
  { no: 276, name: "starnight sevent", school: "SMAN 7 Surabaya", session: 2 },
  { no: 277, name: "Tim Helium", school: "SMA Negeri 1 Kademangan", session: 2 },
  { no: 278, name: "Valyra", school: "SMA Negeri 21 Makassar", session: 2 },
  { no: 279, name: "chickendinner", school: "SMA AL WILDAN 1 GADING SERPONG", session: 2 },
  { no: 280, name: "Trio MACAN", school: "SMA Pesat", session: 2 },
  { no: 281, name: "kami cinta fisika", school: "SMA Kristen Petra Acitya", session: 2 },
  { no: 282, name: "Tim NexaMed Kosayu", school: "SMAK Kolese Santo Yusup Malang", session: 2 },
  { no: 283, name: "MABA Biomedik 2027", school: "SMA NEGERI 16 SURABAYA", session: 2 },
  { no: 284, name: "Amorphophallus", school: "SMA Negeri 22 Surabaya", session: 2 },
  { no: 285, name: "BISMILLAH SUKSES", school: "SMA Negeri 1 Pontianak", session: 2 },
  { no: 286, name: "YakinTim", school: "SMA Muhammadiyah 10 Gresik", session: 2 },
  { no: 287, name: "CibroK", school: "SMA Muhammadiyah 2 Surabaya", session: 2 },
  { no: 288, name: "AK-47", school: "SMA Kristen Petra 2", session: 2 },
  { no: 289, name: "SailorMoon", school: "SMA NEGERI 15 SURABAYA", session: 2 },
  { no: 290, name: "AVAAN TUH", school: "SMAK St. Louis 1 Surabaya", session: 2 },
  { no: 291, name: "SONIC SMANSA", school: "SMA Negeri 1 Pamekasan", session: 2 },
  { no: 292, name: "Pecelele", school: "SMA Regina Pacis Surakarta", session: 2 },
  { no: 293, name: "#CIDOforever>_<", school: "SMA Negeri 1 Tuban", session: 2 },
  { no: 294, name: "Tim Hacnafar", school: "SMA Negeri 2 Sidoarjo", session: 2 },
  { no: 295, name: "alhamdulillah", school: "SMA Muhammadiyah 10 GKB Gresik", session: 2 },
  { no: 296, name: "The Fighter Of Blue", school: "SMA NEGERI 1 MANYAR", session: 2 },
  { no: 297, name: "ngga tau", school: "SMA Katolik St. Louis 1 Surabaya", session: 2 },
  { no: 298, name: "Medivox", school: "SMAK Kolese Santo Yusup Malang", session: 2 },
  { no: 299, name: "AERIS", school: "SMA Negeri 1 Pamekasan", session: 2 },
  { no: 300, name: "WE ATE", school: "SMA Negeri 1 Geger", session: 2 },
  { no: 301, name: "SigSeven", school: "SMA Negeri 1 Karawang", session: 2 },
  { no: 302, name: "Trinity", school: "SMA Negeri 1 Yogyakarta", session: 2 },
  { no: 303, name: "gatau", school: "SMAK Kolese Santo Yusup", session: 2 },
  { no: 304, name: "Comic 3 Revolution", school: "SMAK Kolese St. Yusuf", session: 2 },
  { no: 305, name: "Tekedfarm", school: "SMA Kristen Gloria 2", session: 2 },
  { no: 306, name: "Bolu Ketan", school: "SMA Negeri 1 Sooko", session: 2 },
  { no: 307, name: "Neuvoria", school: "SMA Negeri 2 Lamongan", session: 2 },
  { no: 308, name: "una ir im coming", school: "SMA NEGERI 16 SURABAYA", session: 2 },
  { no: 309, name: "Newbies", school: "MAN 1 KOTA MALANG", session: 2 },
  { no: 310, name: "Basmallah", school: "MA Unggulan Amanatul Ummah Program MBI", session: 2 },
  { no: 311, name: "Tim D", school: "SMA Katolik Kolese Santo Yusup Malang", session: 2 },
  { no: 312, name: "Tim Smansazen", school: "SMA Negeri 1 Sumenep", session: 2 },
  { no: 313, name: "ANATICA", school: "MAN Sidoarjo", session: 2 },
  { no: 314, name: "Trio Sugeh", school: "SMA Negeri 1 Sumenep", session: 2 },
  { no: 315, name: "BioPioneers", school: "SMAN 1 PASIRIAN", session: 2 },
  { no: 316, name: "Vector Triad", school: "SMA Negeri Kabuh", session: 2 },
  { no: 317, name: "Beyond Average", school: "Smas Sunan Giri", session: 2 },
  { no: 318, name: "Tim Unsur", school: "SMAS Katholik Untung Surapati Sidoarjo", session: 2 },
  { no: 319, name: "Juara 1 BMEC 2026", school: "SMA Negeri 1 Ngunut", session: 2 },
  { no: 320, name: "Swaraya", school: "SMA Negeri 1 Srengat", session: 2 },
  { no: 321, name: "Tim Bolu Ketan", school: "SMA Negeri 1 Sumenep", session: 2 },
  { no: 322, name: "Tim Biomedis Tara", school: "SMA Taman Rama Denpasar", session: 2 },
  { no: 323, name: "Medallion", school: "SMA Negeri 2 Kota Kediri", session: 2 },
  { no: 324, name: "Error_404!", school: "SMAN 2 TRENGGALEK", session: 2 },
  { no: 325, name: "BSK MODE ON", school: "SMA Negeri 1 Kedamean", session: 2 },
  { no: 326, name: "Trio macan rawr", school: "Man 1 Batam", session: 2 },
  { no: 327, name: "gaspol", school: "SMA Muhammadiyah 2 Surabaya", session: 2 },
  { no: 328, name: "Tim AT+PY", school: "SMA Kristen Petra Acitya", session: 2 },
  { no: 329, name: "WM", school: "SMA Negeri 15 Surabaya", session: 2 },
  { no: 330, name: "Tim Jamu", school: "SMAS JAKARTA ISLAMIC SCHOOL", session: 2 },
  { no: 331, name: "woylesgo", school: "SMA NEGERI 1 GLAGAH", session: 2 },
  { no: 332, name: "Alchevra", school: "SMA Negeri 1 Purwosari", session: 2 },
  { no: 333, name: "Healthy Generation", school: "SMAN 02 BONDOWOSO", session: 2 },
  { no: 334, name: "Tra Rat Tar", school: "SMAN 18 KOTA BEKASI", session: 2 },
  { no: 335, name: "Foton", school: "MAN 2 Kudus", session: 2 },
  { no: 336, name: "NaCl bukan cinta", school: "MAN 2 Kota Probolinggo", session: 2 },
  { no: 337, name: "IJO LUMUT", school: "SMA WARDAYA", session: 2 },
  { no: 338, name: "SHADILIS'26", school: "MA Negeri Sidoarjo", session: 2 },
  { no: 339, name: "Bravo Tigas", school: "SMA Negeri 3 Malang", session: 2 },
  { no: 340, name: "CAKIYA BLESSED", school: "SMA NEGERI 2 PURWOKERTO", session: 2 },
  { no: 341, name: "Abomination", school: "SMA Bintang Pelajar Islamic Boarding School", session: 2 },
  { no: 342, name: "Airlangga Cabang Ganesha", school: "SMA Negeri 3 Semarang", session: 2 },
  { no: 343, name: "S1N", school: "SMA Negeri 1 Ngawi", session: 2 },
  { no: 344, name: "Blengerrr", school: "SMA Negeri 3 Surakarta", session: 2 },
  { no: 345, name: "MPI(Mas Pigai Imut)", school: "SMA Negeri 1 Tambakboyo", session: 2 },
  { no: 346, name: "Powerpuff Girls", school: "SMAK Kolese Santo Yusup", session: 2 },
  { no: 347, name: "Tim Biotechnice", school: "SMA NEGERI 2 KOTA KEDIRI", session: 2 },
  { no: 348, name: "Trio Al-Fatih CRZ", school: "MAN 2 KOTA PROBOLINGGO", session: 2 },
  { no: 349, name: "yabba-dabba-doo", school: "SMA AL MUSLIM SIDOARJO", session: 2 },
  { no: 350, name: "TRIO DNA", school: "SMA NEGERI 1 KOTA KEDIRI", session: 2 },
];
